# Generated by Django 4.1 on 2024-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0002_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='happiness.tag'),
        ),
    ]
