# Generated by Django 4.1 on 2024-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
