# Generated by Django 4.1 on 2024-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='emoji',
            field=models.CharField(default='😀', max_length=1),
        ),
    ]
